Repository web-vision/deepltranslate-core, pull requests merged in 2024-12, with the labels that each got.

#386 [TASK] Ensure `TestCase::setUp()` parent call chain in tests
  Tests/Unit/Access/AllowedGlossarySyncAccessTest.php
  Tests/Unit/Access/AllowedTranslateAccessTest.php
Labels: task

#397 [BUGFIX] Ender preview translated flag information in TYPO3 v12
  Build/phpstan/Core11/phpstan-baseline.neon
  Build/phpstan/Core11/phpstan.neon
  Build/phpstan/Core12/phpstan-baseline.neon
  Build/phpstan/Core12/phpstan.neon
  Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
  Configuration/Services.php
  ext_localconf.php
Labels: Version 4.x

#398 [BUGFIX] Ender preview translated flag information in TYPO3 v12 (5.x)
  Build/phpstan/Core12/phpstan-baseline.neon
  Build/phpstan/Core12/phpstan.neon
  Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
  Configuration/Services.php
  ext_localconf.php
Labels: Version 5.x

#399 [!!!][TASK] Remove obsolete `DeeplPreviewFlagGeneratePageHook`
  Classes/Event/Listener/RenderTranslatedFlagInFrontendPreviewMode.php
  Classes/Hooks/DeeplPreviewFlagGeneratePageHook.php
  Configuration/Services.php
  ext_localconf.php
Labels: task, breaking, Version 5.x

#403 [TASK] Make ProcessingInstructions public service for 4.x
  Configuration/Services.php
Labels: Version 4.x, Version 5.x
